server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  application:
    name: jark

logging:
  config: classpath:logback/logback-${spring.profiles.active:dev}.xml
management:
  endpoints:
    web:
      base-path: /actuator #配置端点访问前缀
      exposure:
        include: '*' #暴露所有端点